Added ability to configurate the argparser using an `ARGPARSER_CONFIGURATION_FILE`

diff --git a/argparser b/argparser
--- a/argparser
+++ b/argparser
@@ -4,8 +4,7 @@
 # E-Mail: simon.brandt@uni-greifswald.de
 # Last Modification: 2025-02-21
 
-# TODO: Support argparser configuration by command-line arguments and
-#       config file.
+# TODO: Support argparser configuration by command-line arguments.
 # TODO: Remove double meaning of "--" both for configuring the argparser
 #       and as normal command-line option.
 # TODO: Rewrite tests as correct test suites.
@@ -27,87 +26,6 @@
 # the README.md for details.
 
 ########################################################################
-
-# Set the argparser environment variables, as long as they aren't
-# already set by the calling script or environment (to prevent
-# overriding them).  The no-op command ":" is used for its side effect
-# to set the variables, if unset or null, as part of the parameter
-# expansion.
-if (( "$#" >= 2 )) && [[ "$2" == "--" ]]; then
-    case "$1" in
-        "--read")
-            ARGPARSER_READ_ARGS=true
-            ARGPARSER_SET_ARGS=false
-            ;;
-        "--set")
-            ARGPARSER_READ_ARGS=false
-            ARGPARSER_SET_ARGS=true
-            ;;
-        "--all")
-            ARGPARSER_READ_ARGS=true
-            ARGPARSER_SET_ARGS=true
-            ;;
-        *)
-            printf 'Error: Wrong action given: %s\n' "$1"
-            exit 1
-            ;;
-    esac
-    shift 2  # Get rid of the action specification.
-fi
-if [[ -v ARGPARSER_DICTIONARY ]]; then
-    printf 'Error: ARGPARSER_DICTIONARY must not be set.\n'
-    exit 1
-else
-    declare -A ARGPARSER_DICTIONARY
-fi
-: "${ARGPARSER_ADD_HELP:=true}"
-: "${ARGPARSER_ADD_USAGE:=true}"
-: "${ARGPARSER_ADD_VERSION:=true}"
-: "${ARGPARSER_ALLOW_OPTION_ABBREVIATION:=false}"
-: "${ARGPARSER_ALLOW_OPTION_MERGING:=false}"
-: "${ARGPARSER_ARG_ARRAY_NAME:="args"}"
-: "${ARGPARSER_ARG_DEF_FILE:=""}"
-: "${ARGPARSER_ARG_DEF_FILE_HAS_HEADER:=true}"
-: "${ARGPARSER_ARG_DEF_HAS_HEADER:=true}"
-: "${ARGPARSER_ARG_DELIMITER_1:=":"}"
-: "${ARGPARSER_ARG_DELIMITER_2:=","}"
-: "${ARGPARSER_CHECK_ARG_DEFINITION:=false}"
-: "${ARGPARSER_CHECK_ENV_VARS:=false}"
-: "${ARGPARSER_COUNT_FLAGS:=false}"
-: "${ARGPARSER_ERROR_EXIT_CODE:=1}"
-: "${ARGPARSER_ERROR_STYLE:="red,bold,reverse"}"
-: "${ARGPARSER_HELP_EXIT_CODE:=0}"
-: "${ARGPARSER_HELP_FILE:=""}"
-: "${ARGPARSER_HELP_FILE_INCLUDE_CHAR:="@"}"
-: "${ARGPARSER_HELP_FILE_KEEP_COMMENTS:=false}"
-: "${ARGPARSER_HELP_STYLE:="italic"}"
-: "${ARGPARSER_LANGUAGE:="en"}"
-: "${ARGPARSER_MAX_COL_WIDTH_1:=5}"
-: "${ARGPARSER_MAX_COL_WIDTH_2:=33}"
-: "${ARGPARSER_MAX_COL_WIDTH_3:=39}"
-: "${ARGPARSER_POSITIONAL_ARG_GROUP:="Positional arguments"}"
-: "${ARGPARSER_READ_ARGS:=true}"
-: "${ARGPARSER_SCRIPT_NAME:="${0##*/}"}"
-: "${ARGPARSER_SET_ARGS:=true}"
-: "${ARGPARSER_SET_ARRAYS:=true}"
-: "${ARGPARSER_SILENCE_ERRORS:=false}"
-: "${ARGPARSER_SILENCE_WARNINGS:=false}"
-: "${ARGPARSER_TRANSLATION_FILE:=""}"
-: "${ARGPARSER_UNSET_ARGS:=true}"
-: "${ARGPARSER_UNSET_ENV_VARS:=true}"
-: "${ARGPARSER_UNSET_FUNCTIONS:=true}"
-: "${ARGPARSER_USAGE_EXIT_CODE:=0}"
-: "${ARGPARSER_USAGE_FILE:=""}"
-: "${ARGPARSER_USAGE_FILE_INCLUDE_CHAR:="@"}"
-: "${ARGPARSER_USAGE_FILE_KEEP_COMMENTS:=false}"
-: "${ARGPARSER_USAGE_MESSAGE_OPTION_TYPE:="short"}"
-: "${ARGPARSER_USAGE_MESSAGE_ORIENTATION:="row"}"
-: "${ARGPARSER_USAGE_STYLE:="italic"}"
-: "${ARGPARSER_USE_STYLES_IN_FILES:=false}"
-: "${ARGPARSER_VERSION:="1.0.0"}"
-: "${ARGPARSER_VERSION_EXIT_CODE:=0}"
-: "${ARGPARSER_VERSION_STYLE:="bold"}"
-: "${ARGPARSER_WARNING_STYLE:="red,bold"}"
 
 # Define the argparser functions used for general tests.
 function argparser_in_array() {
@@ -709,8 +627,293 @@ function argparser_colorize() {
     fi
 }
 
-# Define the argparser functions for checking the environment variables
-# and reading, parsing, and checking the arguments definition.
+# Define the argparser functions for reading the configuration file and
+# setting and checking the environment variables.
+function argparser_read_configuration() {
+    # Read the configuratioon from the configuration file into the
+    # environment variables.
+    #
+    # Environment:
+    # ARGPARSER_ADD_HELP
+    # ARGPARSER_ADD_USAGE
+    # ARGPARSER_ADD_VERSION
+    # ARGPARSER_ALLOW_OPTION_ABBREVIATION
+    # ARGPARSER_ALLOW_OPTION_MERGING
+    # ARGPARSER_ARG_ARRAY_NAME
+    # ARGPARSER_ARG_DEF_FILE
+    # ARGPARSER_ARG_DEF_FILE_HAS_HEADER
+    # ARGPARSER_ARG_DEF_HAS_HEADER
+    # ARGPARSER_ARG_DELIMITER_1
+    # ARGPARSER_ARG_DELIMITER_2
+    # ARGPARSER_CHECK_ARG_DEFINITION
+    # ARGPARSER_CHECK_ENV_VARS
+    # ARGPARSER_CONFIGURATION_FILE
+    # ARGPARSER_COUNT_FLAGS
+    # ARGPARSER_DICTIONARY
+    # ARGPARSER_ERROR_EXIT_CODE
+    # ARGPARSER_ERROR_STYLE
+    # ARGPARSER_HELP_EXIT_CODE
+    # ARGPARSER_HELP_FILE
+    # ARGPARSER_HELP_FILE_INCLUDE_CHAR
+    # ARGPARSER_HELP_FILE_KEEP_COMMENTS
+    # ARGPARSER_HELP_STYLE
+    # ARGPARSER_LANGUAGE
+    # ARGPARSER_MAX_COL_WIDTH_1
+    # ARGPARSER_MAX_COL_WIDTH_2
+    # ARGPARSER_MAX_COL_WIDTH_3
+    # ARGPARSER_POSITIONAL_ARG_GROUP
+    # ARGPARSER_READ_ARGS
+    # ARGPARSER_SCRIPT_NAME
+    # ARGPARSER_SET_ARGS
+    # ARGPARSER_SET_ARRAYS
+    # ARGPARSER_SILENCE_ERRORS
+    # ARGPARSER_SILENCE_WARNINGS
+    # ARGPARSER_TRANSLATION_FILE
+    # ARGPARSER_UNSET_ARGS
+    # ARGPARSER_UNSET_ENV_VARS
+    # ARGPARSER_UNSET_FUNCTIONS
+    # ARGPARSER_USAGE_EXIT_CODE
+    # ARGPARSER_USAGE_FILE
+    # ARGPARSER_USAGE_FILE_INCLUDE_CHAR
+    # ARGPARSER_USAGE_FILE_KEEP_COMMENTS
+    # ARGPARSER_USAGE_MESSAGE_OPTION_TYPE
+    # ARGPARSER_USAGE_MESSAGE_ORIENTATION
+    # ARGPARSER_USAGE_STYLE
+    # ARGPARSER_USE_STYLES_IN_FILES
+    # ARGPARSER_VERSION
+    # ARGPARSER_VERSION_EXIT_CODE
+    # ARGPARSER_VERSION_STYLE
+    # ARGPARSER_WARNING_STYLE
+
+    # Define the local variables.
+    local attributes
+    local error_message
+    local -a error_messages
+    local is_extglob_set
+    local line
+    local -a lines
+    local value
+    local var
+
+    # Locally disable errexit and enable extglob.
+    local -
+    set +o errexit
+    is_extglob_set="$(shopt -p extglob)"
+    shopt -s extglob
+
+    # Check if the configuration file exists and is readable.  Else,
+    # output an error message and exit.  Since at this point of
+    # invokation, the environment variables aren't checked, yet, set the
+    # needed ones to default values, if ${ARGPARSER_CHECK_ENV_VARS}
+    # isn't set to false (and by this, the checking hasn't been
+    # explicitly disabled).
+    attributes="$(argparser_check_file "${ARGPARSER_CONFIGURATION_FILE}")"
+    if [[ "${attributes}" != 0000 ]]; then
+        error_message="Error: The environment variable \"%s\" is set to "
+        error_message+="\"%s\", but the referenced file "
+        case "${attributes}" in
+            0001) error_message+="is empty." ;;
+            0010) error_message+="is not readable." ;;
+            0011) error_message+="is not readable and empty." ;;
+            0100) error_message+="is not a regular file." ;;
+            0101) error_message+="is not a regular file and empty." ;;
+            0110)
+                error_message+="is not a regular file and not readable."
+                ;;
+            0111)
+                error_message+="is not a regular file, not readable, and "
+                error_message+="empty."
+                ;;
+            1111) error_message+="does not exist." ;;
+        esac
+        error_message="${error_message/"%s"/"ARGPARSER_CONFIGURATION_FILE"}"
+        error_message="${error_message/"%s"/${ARGPARSER_CONFIGURATION_FILE}}"
+
+        if [[ "${ARGPARSER_CHECK_ENV_VARS}" != false ]]; then
+            ARGPARSER_ERROR_EXIT_CODE=1
+            ARGPARSER_ERROR_STYLE="red,bold,reverse"
+        fi
+        argparser_print_error_or_warning_message "error" false true \
+            "${error_message}"
+    fi
+
+    # Read the configuration file.
+    mapfile -t lines < "${ARGPARSER_CONFIGURATION_FILE}"
+    error_messages=( )
+
+    for line in "${lines[@]}"; do
+        if [[ -z "${line}" || "${line}" == \#* ]]; then
+            # Ignore the empty or commented line.
+            continue
+        elif [[ "${line}" =~ = ]]; then
+            # Set the variable name as shortest part before an equals
+            # sign ("="), strip leading and trailing spaces, replace
+            # hyphens and spaces by underscores, capitalize the variable
+            # name, and prepend the string "ARGPARSER_".  Then, extract
+            # the value as longest part after the equals sign and strip
+            # leading and trailing spaces and a double quote each.
+            var="${line%%=*}"
+            var="${var##+( )}"
+            var="${var%%+( )}"
+            var="${var//-/_}"
+            var="${var// /_}"
+            var="ARGPARSER_${var^^}"
+
+            value="${line#*=}"
+            value="${value##+( )}"
+            value="${value%%+( )}"
+            value="${value#\"}"
+            value="${value%\"}"
+
+            # Set the environment variable, as long as it isn't already
+            # set by the calling script or environment to prevent
+            # overriding it.
+            if [[ ! -v "${var}" ]]; then
+                declare -g "${var}"="${value}"
+            fi
+        else
+            # Output an error message when the line doesn't contain an
+            # equals sign ("=").
+            error_message="Error: The line \"%s\" doesn't contain an equals "
+            error_message+="sign (\"=\"), nor is it empty or commented."
+            error_message="${error_message/"%s"/"${line}"}"
+            error_messages+=("${error_message}")
+        fi
+    done
+
+    # Depending on the value of ${is_extglob_set}, which uses shopt's
+    # feature of storing the extglob state in a format reusable as
+    # input, possibly disable extglob.
+    eval "${is_extglob_set}"
+
+    # Colorize, sort, filter, and print all error messages, then exit,
+    # as the environment variables should be correctly read.
+    argparser_print_error_or_warning_message "error" true true \
+        "${error_messages[@]}"
+}
+
+function argparser_set_env_vars() {
+    # Set the argparser environment variables, as long as they aren't
+    # already set by the calling script or environment to prevent
+    # overriding them.
+    #
+    # Arguments:
+    # - $@: the command line upon sourcing the argparser
+    #
+    # Environment:
+    # ARGPARSER_ADD_HELP
+    # ARGPARSER_ADD_USAGE
+    # ARGPARSER_ADD_VERSION
+    # ARGPARSER_ALLOW_OPTION_ABBREVIATION
+    # ARGPARSER_ALLOW_OPTION_MERGING
+    # ARGPARSER_ARG_ARRAY_NAME
+    # ARGPARSER_ARG_DEF_FILE
+    # ARGPARSER_ARG_DEF_FILE_HAS_HEADER
+    # ARGPARSER_ARG_DEF_HAS_HEADER
+    # ARGPARSER_ARG_DELIMITER_1
+    # ARGPARSER_ARG_DELIMITER_2
+    # ARGPARSER_CHECK_ARG_DEFINITION
+    # ARGPARSER_CHECK_ENV_VARS
+    # ARGPARSER_CONFIGURATION_FILE
+    # ARGPARSER_COUNT_FLAGS
+    # ARGPARSER_DICTIONARY
+    # ARGPARSER_ERROR_EXIT_CODE
+    # ARGPARSER_ERROR_STYLE
+    # ARGPARSER_HELP_EXIT_CODE
+    # ARGPARSER_HELP_FILE
+    # ARGPARSER_HELP_FILE_INCLUDE_CHAR
+    # ARGPARSER_HELP_FILE_KEEP_COMMENTS
+    # ARGPARSER_HELP_STYLE
+    # ARGPARSER_LANGUAGE
+    # ARGPARSER_MAX_COL_WIDTH_1
+    # ARGPARSER_MAX_COL_WIDTH_2
+    # ARGPARSER_MAX_COL_WIDTH_3
+    # ARGPARSER_POSITIONAL_ARG_GROUP
+    # ARGPARSER_READ_ARGS
+    # ARGPARSER_SCRIPT_NAME
+    # ARGPARSER_SET_ARGS
+    # ARGPARSER_SET_ARRAYS
+    # ARGPARSER_SILENCE_ERRORS
+    # ARGPARSER_SILENCE_WARNINGS
+    # ARGPARSER_TRANSLATION_FILE
+    # ARGPARSER_UNSET_ARGS
+    # ARGPARSER_UNSET_ENV_VARS
+    # ARGPARSER_UNSET_FUNCTIONS
+    # ARGPARSER_USAGE_EXIT_CODE
+    # ARGPARSER_USAGE_FILE
+    # ARGPARSER_USAGE_FILE_INCLUDE_CHAR
+    # ARGPARSER_USAGE_FILE_KEEP_COMMENTS
+    # ARGPARSER_USAGE_MESSAGE_OPTION_TYPE
+    # ARGPARSER_USAGE_MESSAGE_ORIENTATION
+    # ARGPARSER_USAGE_STYLE
+    # ARGPARSER_USE_STYLES_IN_FILES
+    # ARGPARSER_VERSION
+    # ARGPARSER_VERSION_EXIT_CODE
+    # ARGPARSER_VERSION_STYLE
+    # ARGPARSER_WARNING_STYLE
+
+    # Check that ${ARGPARSER_DICTIONARY} is unset.
+    if [[ -v ARGPARSER_DICTIONARY ]]; then
+        printf 'Error: ARGPARSER_DICTIONARY must not be set.\n'
+        exit 1
+    else
+        declare -g -A ARGPARSER_DICTIONARY
+    fi
+
+    # Set the remaining environment variables.  The no-op command ":" is
+    # used for its side effect to set the variables, if unset or null,
+    # as part of the parameter expansion.
+    : "${ARGPARSER_ADD_HELP:=true}"
+    : "${ARGPARSER_ADD_USAGE:=true}"
+    : "${ARGPARSER_ADD_VERSION:=true}"
+    : "${ARGPARSER_ALLOW_OPTION_ABBREVIATION:=false}"
+    : "${ARGPARSER_ALLOW_OPTION_MERGING:=false}"
+    : "${ARGPARSER_ARG_ARRAY_NAME:="args"}"
+    : "${ARGPARSER_ARG_DEF_FILE:=""}"
+    : "${ARGPARSER_ARG_DEF_FILE_HAS_HEADER:=true}"
+    : "${ARGPARSER_ARG_DEF_HAS_HEADER:=true}"
+    : "${ARGPARSER_ARG_DELIMITER_1:=":"}"
+    : "${ARGPARSER_ARG_DELIMITER_2:=","}"
+    : "${ARGPARSER_CHECK_ARG_DEFINITION:=false}"
+    : "${ARGPARSER_CHECK_ENV_VARS:=false}"
+    : "${ARGPARSER_CONFIGURATION_FILE:=""}"
+    : "${ARGPARSER_COUNT_FLAGS:=false}"
+    : "${ARGPARSER_ERROR_EXIT_CODE:=1}"
+    : "${ARGPARSER_ERROR_STYLE:="red,bold,reverse"}"
+    : "${ARGPARSER_HELP_EXIT_CODE:=0}"
+    : "${ARGPARSER_HELP_FILE:=""}"
+    : "${ARGPARSER_HELP_FILE_INCLUDE_CHAR:="@"}"
+    : "${ARGPARSER_HELP_FILE_KEEP_COMMENTS:=false}"
+    : "${ARGPARSER_HELP_STYLE:="italic"}"
+    : "${ARGPARSER_LANGUAGE:="en"}"
+    : "${ARGPARSER_MAX_COL_WIDTH_1:=5}"
+    : "${ARGPARSER_MAX_COL_WIDTH_2:=33}"
+    : "${ARGPARSER_MAX_COL_WIDTH_3:=39}"
+    : "${ARGPARSER_POSITIONAL_ARG_GROUP:="Positional arguments"}"
+    : "${ARGPARSER_READ_ARGS:=true}"
+    : "${ARGPARSER_SCRIPT_NAME:="${0##*/}"}"
+    : "${ARGPARSER_SET_ARGS:=true}"
+    : "${ARGPARSER_SET_ARRAYS:=true}"
+    : "${ARGPARSER_SILENCE_ERRORS:=false}"
+    : "${ARGPARSER_SILENCE_WARNINGS:=false}"
+    : "${ARGPARSER_TRANSLATION_FILE:=""}"
+    : "${ARGPARSER_UNSET_ARGS:=true}"
+    : "${ARGPARSER_UNSET_ENV_VARS:=true}"
+    : "${ARGPARSER_UNSET_FUNCTIONS:=true}"
+    : "${ARGPARSER_USAGE_EXIT_CODE:=0}"
+    : "${ARGPARSER_USAGE_FILE:=""}"
+    : "${ARGPARSER_USAGE_FILE_INCLUDE_CHAR:="@"}"
+    : "${ARGPARSER_USAGE_FILE_KEEP_COMMENTS:=false}"
+    : "${ARGPARSER_USAGE_MESSAGE_OPTION_TYPE:="short"}"
+    : "${ARGPARSER_USAGE_MESSAGE_ORIENTATION:="row"}"
+    : "${ARGPARSER_USAGE_STYLE:="italic"}"
+    : "${ARGPARSER_USE_STYLES_IN_FILES:=false}"
+    : "${ARGPARSER_VERSION:="1.0.0"}"
+    : "${ARGPARSER_VERSION_EXIT_CODE:=0}"
+    : "${ARGPARSER_VERSION_STYLE:="bold"}"
+    : "${ARGPARSER_WARNING_STYLE:="red,bold"}"
+}
+
 function argparser_check_env_vars() {
     # Check if the argparser envirnoment variables accord to their
     # definition.  This should always be true for production scripts,
@@ -738,6 +941,7 @@ function argparser_check_env_vars() {
     # - ARGPARSER_ARG_DELIMITER_2 (read-only)
     # - ARGPARSER_CHECK_ARG_DEFINITION (read-only)
     # - ARGPARSER_CHECK_ENV_VARS (read-only)
+    # - ARGPARSER_CONFIGURATION_FILE (read-only)
     # - ARGPARSER_COUNT_FLAGS (read-only)
     # - ARGPARSER_ERROR_EXIT_CODE
     # - ARGPARSER_ERROR_STYLE
@@ -992,11 +1196,12 @@ function argparser_check_env_vars() {
         error_messages+=("${error_message}")
     fi
 
-    # Then, check that the arguments definition file, the help file, the
-    # translation file, and the usage file are different from each
-    # other, if given.
+    # Then, check that the arguments definition file, the configuration
+    # file, the help file, the translation file, and the usage file are
+    # different from each other, if given.
     vars=(
         ARGPARSER_ARG_DEF_FILE
+        ARGPARSER_CONFIGURATION_FILE
         ARGPARSER_HELP_FILE
         ARGPARSER_TRANSLATION_FILE
         ARGPARSER_USAGE_FILE
@@ -1032,6 +1237,8 @@ function argparser_check_env_vars() {
         "${error_messages[@]}"
 }
 
+# Define the argparser functions for reading, parsing, and checking the
+# arguments definition.
 function argparser_read_args_definition() {
     # Read the arguments definition from the script and arguments
     # definition file, if provided.
@@ -5338,6 +5545,42 @@ function argparser_main() {
     eval "${is_extglob_set}"
 }
 
+# Read the action specification for the argparser.
+if (( "$#" >= 2 )) && [[ "$2" == "--" ]]; then
+    case "$1" in
+        "--read")
+            ARGPARSER_READ_ARGS=true
+            ARGPARSER_SET_ARGS=false
+            ;;
+        "--set")
+            ARGPARSER_READ_ARGS=false
+            ARGPARSER_SET_ARGS=true
+            ;;
+        "--all")
+            ARGPARSER_READ_ARGS=true
+            ARGPARSER_SET_ARGS=true
+            ;;
+        *)
+            printf 'Error: Wrong action given: %s\n' "$1"
+            exit 1
+            ;;
+    esac
+
+    # Get rid of the action specification.
+    shift 2
+fi
+
+# If ${ARGPARSER_CONFIGURATION_FILE} is defined and not set to the empty
+# string, read the configuration file.  Then, set the environment
+# variables that aren't already set by the calling script or environment
+# or read from the configuration file to prevent overriding them.
+if [[ -v ARGPARSER_CONFIGURATION_FILE \
+    && -n "${ARGPARSER_CONFIGURATION_FILE}" ]]
+then
+    argparser_read_configuration
+fi
+argparser_set_env_vars "$@"
+
 # If ${ARGPARSER_TRANSLATION_FILE} isn't set to the empty string, read
 # the translation file.  To be able to use the localized name of
 # ${ARGPARSER_POSITIONAL_ARG_GROUP} in the arguments definition and help
@@ -5415,7 +5658,9 @@ if [[ "${ARGPARSER_UNSET_FUNCTIONS}" == true ]]; then
     unset -f argparser_print_version_message
     unset -f argparser_quicksort
     unset -f argparser_read_args_definition
+    unset -f argparser_read_configuration
     unset -f argparser_read_translation
+    unset -f argparser_set_env_vars
     unset -f argparser_sort
     unset -f argparser_translate
     unset -f argparser_trim
@@ -5440,6 +5685,7 @@ if [[ "${ARGPARSER_UNSET_ENV_VARS}" == true ]]; then
     unset ARGPARSER_ARG_DELIMITER_2
     unset ARGPARSER_CHECK_ARG_DEFINITION
     unset ARGPARSER_CHECK_ENV_VARS
+    unset ARGPARSER_CONFIGURATION_FILE
     unset ARGPARSER_COUNT_FLAGS
     unset ARGPARSER_DICTIONARY
     unset ARGPARSER_ERROR_EXIT_CODE
